### ISSUE TITLE
Runner v2.273.6 start to error out due to ::set-env name

### ISSUE THREAD

**Issue by dominikmeyersap** [actions/setup-java#125]
**Description:**
Starting with runner versions >2.273.6 the runners error out if the syntax `::set-env` is used.

**Task version:**
1.4.3

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [ ] Hosted
- [x] Self-hosted, version: 2.277.1

**Repro steps:**  
Take any runner above 2.273.6 and setup-java, e.g. with:

```
      - name: Configure java 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          server-id: maven-public
          server-username: NEXUS_USER
          server-password: NEXUS_PASSWORD
```

**Expected behavior:**
Works.

**Actual behavior:**
Errors out with:
```
::set-env name=JAVA_HOME_11_0_10_X64::/opt/hostedtoolcache/jdk/11.0.10/x64
##[error]Unable to process command '::set-env name=JAVA_HOME_11_0_10_X64::/opt/hostedtoolcache/jdk/11.0.10/x64' successfully.
##[error]The `set-env` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
##[debug]System.Exception: The `set-env` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
##[debug]   at GitHub.Runner.Worker.SetEnvCommandExtension.ProcessCommand(IExecutionContext context, String line, ActionCommand command, ContainerInfo container)
##[debug]   at GitHub.Runner.Worker.ActionCommandManager.TryProcessCommand(IExecutionContext context, String input, ContainerInfo container)
::add-path::/opt/hostedtoolcache/jdk/11.0.10/x64/bin
##[error]Unable to process command '::add-path::/opt/hostedtoolcache/jdk/11.0.10/x64/bin' successfully.
##[error]The `add-path` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```

Due to:
https://github.com/actions/runner/pull/779
https://github.com/actions/runner/pull/784

**Comment by maxim-lobanov** [comment]
Hello @dominikmeyersap ,
This task was updated to use environments files 5 months ago via https://github.com/actions/setup-java/pull/104
Both `v1` and `v1.4.3` contains these changes. Also I can't reproduce it on Hosted runner.

Do you use GitHub Enterprise? (as far as I know it requires [manual sync of task version](https://github.com/actions/actions-sync))

**Comment by dominikmeyersap** [comment]
🤦‍♂️ 🤒  Of course we do and I just updated the version and it worked. Please disregard we did not see the 5 letters difference in the path and wondered. How on earth is it possible that no one reported that 💯
